// Code generated by MockGen. DO NOT EDIT.
// Source: lama-backend/domain/repositories (interfaces: IUsersRepository,IOwnerRepository,ICaretakerRepository,IDoctorRepository,IPetRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "lama-backend/domain/entities"
	db "lama-backend/domain/prisma/db"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockIUsersRepository is a mock of IUsersRepository interface.
type MockIUsersRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUsersRepositoryMockRecorder
}

// MockIUsersRepositoryMockRecorder is the mock recorder for MockIUsersRepository.
type MockIUsersRepositoryMockRecorder struct {
	mock *MockIUsersRepository
}

// NewMockIUsersRepository creates a new mock instance.
func NewMockIUsersRepository(ctrl *gomock.Controller) *MockIUsersRepository {
	mock := &MockIUsersRepository{ctrl: ctrl}
	mock.recorder = &MockIUsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUsersRepository) EXPECT() *MockIUsersRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockIUsersRepository) DeleteByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIUsersRepositoryMockRecorder) DeleteByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIUsersRepository)(nil).DeleteByID), arg0)
}

// FindByEmailAndRole mocks base method.
func (m *MockIUsersRepository) FindByEmailAndRole(arg0, arg1 string) (*entities.LoginUserResponseModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmailAndRole", arg0, arg1)
	ret0, _ := ret[0].(*entities.LoginUserResponseModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmailAndRole indicates an expected call of FindByEmailAndRole.
func (mr *MockIUsersRepositoryMockRecorder) FindByEmailAndRole(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmailAndRole", reflect.TypeOf((*MockIUsersRepository)(nil).FindByEmailAndRole), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockIUsersRepository) FindByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIUsersRepositoryMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIUsersRepository)(nil).FindByID), arg0)
}

// FindAll mocks base method.
func (m *MockIUsersRepository) FindAll(arg0 string, arg1, arg2 int) ([]*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIUsersRepositoryMockRecorder) FindAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIUsersRepository)(nil).FindAll), arg0, arg1, arg2)
}

// InsertUser mocks base method.
func (m *MockIUsersRepository) InsertUser(arg0 string, arg1 entities.CreatedUserModel) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertUser", arg0, arg1)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertUser indicates an expected call of InsertUser.
func (mr *MockIUsersRepositoryMockRecorder) InsertUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertUser", reflect.TypeOf((*MockIUsersRepository)(nil).InsertUser), arg0, arg1)
}

// UpdateByID mocks base method.
func (m *MockIUsersRepository) UpdateByID(arg0 string, arg1 entities.UpdateUserModel) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0, arg1)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIUsersRepositoryMockRecorder) UpdateByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIUsersRepository)(nil).UpdateByID), arg0, arg1)
}

// MockIOwnerRepository is a mock of IOwnerRepository interface.
type MockIOwnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOwnerRepositoryMockRecorder
}

// MockIOwnerRepositoryMockRecorder is the mock recorder for MockIOwnerRepository.
type MockIOwnerRepositoryMockRecorder struct {
	mock *MockIOwnerRepository
}

// NewMockIOwnerRepository creates a new mock instance.
func NewMockIOwnerRepository(ctrl *gomock.Controller) *MockIOwnerRepository {
	mock := &MockIOwnerRepository{ctrl: ctrl}
	mock.recorder = &MockIOwnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOwnerRepository) EXPECT() *MockIOwnerRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockIOwnerRepository) DeleteByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIOwnerRepositoryMockRecorder) DeleteByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIOwnerRepository)(nil).DeleteByID), arg0)
}

// FindByID mocks base method.
func (m *MockIOwnerRepository) FindByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIOwnerRepositoryMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIOwnerRepository)(nil).FindByID), arg0)
}

// InsertOwner mocks base method.
func (m *MockIOwnerRepository) InsertOwner(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOwner", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertOwner indicates an expected call of InsertOwner.
func (mr *MockIOwnerRepositoryMockRecorder) InsertOwner(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOwner", reflect.TypeOf((*MockIOwnerRepository)(nil).InsertOwner), arg0)
}

// UpdateByID mocks base method.
func (m *MockIOwnerRepository) UpdateByID(arg0 string, arg1 entities.UpdateUserModel) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0, arg1)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIOwnerRepositoryMockRecorder) UpdateByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIOwnerRepository)(nil).UpdateByID), arg0, arg1)
}

// MockICaretakerRepository is a mock of ICaretakerRepository interface.
type MockICaretakerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockICaretakerRepositoryMockRecorder
}

// MockICaretakerRepositoryMockRecorder is the mock recorder for MockICaretakerRepository.
type MockICaretakerRepositoryMockRecorder struct {
	mock *MockICaretakerRepository
}

// NewMockICaretakerRepository creates a new mock instance.
func NewMockICaretakerRepository(ctrl *gomock.Controller) *MockICaretakerRepository {
	mock := &MockICaretakerRepository{ctrl: ctrl}
	mock.recorder = &MockICaretakerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICaretakerRepository) EXPECT() *MockICaretakerRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockICaretakerRepository) DeleteByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockICaretakerRepositoryMockRecorder) DeleteByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockICaretakerRepository)(nil).DeleteByID), arg0)
}

// FindAvailableCaretaker mocks base method.
func (m *MockICaretakerRepository) FindAvailableCaretaker(arg0, arg1 time.Time) ([]*entities.AvailableStaffResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableCaretaker", arg0, arg1)
	ret0, _ := ret[0].([]*entities.AvailableStaffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableCaretaker indicates an expected call of FindAvailableCaretaker.
func (mr *MockICaretakerRepositoryMockRecorder) FindAvailableCaretaker(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableCaretaker", reflect.TypeOf((*MockICaretakerRepository)(nil).FindAvailableCaretaker), arg0, arg1)
}

// FindBusyTimeSlot mocks base method.
func (m *MockICaretakerRepository) FindBusyTimeSlot(arg0 string, arg1, arg2, arg3, arg4 time.Time) (*[]db.ServiceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBusyTimeSlot", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*[]db.ServiceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBusyTimeSlot indicates an expected call of FindBusyTimeSlot.
func (mr *MockICaretakerRepositoryMockRecorder) FindBusyTimeSlot(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBusyTimeSlot", reflect.TypeOf((*MockICaretakerRepository)(nil).FindBusyTimeSlot), arg0, arg1, arg2, arg3, arg4)
}

// FindByID mocks base method.
func (m *MockICaretakerRepository) FindByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockICaretakerRepositoryMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockICaretakerRepository)(nil).FindByID), arg0)
}

// InsertCaretaker mocks base method.
func (m *MockICaretakerRepository) InsertCaretaker(arg0, arg1 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertCaretaker", arg0, arg1)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertCaretaker indicates an expected call of InsertCaretaker.
func (mr *MockICaretakerRepositoryMockRecorder) InsertCaretaker(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertCaretaker", reflect.TypeOf((*MockICaretakerRepository)(nil).InsertCaretaker), arg0, arg1)
}

// UpdateByID mocks base method.
func (m *MockICaretakerRepository) UpdateByID(arg0 string, arg1 entities.UpdateUserModel) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0, arg1)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockICaretakerRepositoryMockRecorder) UpdateByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockICaretakerRepository)(nil).UpdateByID), arg0, arg1)
}

// MockIDoctorRepository is a mock of IDoctorRepository interface.
type MockIDoctorRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIDoctorRepositoryMockRecorder
}

// MockIDoctorRepositoryMockRecorder is the mock recorder for MockIDoctorRepository.
type MockIDoctorRepositoryMockRecorder struct {
	mock *MockIDoctorRepository
}

// NewMockIDoctorRepository creates a new mock instance.
func NewMockIDoctorRepository(ctrl *gomock.Controller) *MockIDoctorRepository {
	mock := &MockIDoctorRepository{ctrl: ctrl}
	mock.recorder = &MockIDoctorRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDoctorRepository) EXPECT() *MockIDoctorRepositoryMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockIDoctorRepository) DeleteByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockIDoctorRepositoryMockRecorder) DeleteByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockIDoctorRepository)(nil).DeleteByID), arg0)
}

// FindAvailableDoctor mocks base method.
func (m *MockIDoctorRepository) FindAvailableDoctor(arg0, arg1 time.Time) ([]*entities.AvailableStaffResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAvailableDoctor", arg0, arg1)
	ret0, _ := ret[0].([]*entities.AvailableStaffResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAvailableDoctor indicates an expected call of FindAvailableDoctor.
func (mr *MockIDoctorRepositoryMockRecorder) FindAvailableDoctor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAvailableDoctor", reflect.TypeOf((*MockIDoctorRepository)(nil).FindAvailableDoctor), arg0, arg1)
}

// FindBusyTimeSlot mocks base method.
func (m *MockIDoctorRepository) FindBusyTimeSlot(arg0 string, arg1, arg2, arg3, arg4 time.Time) (*[]db.ServiceModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBusyTimeSlot", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*[]db.ServiceModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBusyTimeSlot indicates an expected call of FindBusyTimeSlot.
func (mr *MockIDoctorRepositoryMockRecorder) FindBusyTimeSlot(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBusyTimeSlot", reflect.TypeOf((*MockIDoctorRepository)(nil).FindBusyTimeSlot), arg0, arg1, arg2, arg3, arg4)
}

// FindByID mocks base method.
func (m *MockIDoctorRepository) FindByID(arg0 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIDoctorRepositoryMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIDoctorRepository)(nil).FindByID), arg0)
}

// InsertDoctor mocks base method.
func (m *MockIDoctorRepository) InsertDoctor(arg0, arg1 string) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertDoctor", arg0, arg1)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertDoctor indicates an expected call of InsertDoctor.
func (mr *MockIDoctorRepositoryMockRecorder) InsertDoctor(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertDoctor", reflect.TypeOf((*MockIDoctorRepository)(nil).InsertDoctor), arg0, arg1)
}

// UpdateByID mocks base method.
func (m *MockIDoctorRepository) UpdateByID(arg0 string, arg1 entities.UpdateUserModel) (*entities.UserDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0, arg1)
	ret0, _ := ret[0].(*entities.UserDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockIDoctorRepositoryMockRecorder) UpdateByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockIDoctorRepository)(nil).UpdateByID), arg0, arg1)
}

// MockIPetRepository is a mock of IPetRepository interface.
type MockIPetRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPetRepositoryMockRecorder
}

// MockIPetRepositoryMockRecorder is the mock recorder for MockIPetRepository.
type MockIPetRepositoryMockRecorder struct {
	mock *MockIPetRepository
}

// NewMockIPetRepository creates a new mock instance.
func NewMockIPetRepository(ctrl *gomock.Controller) *MockIPetRepository {
	mock := &MockIPetRepository{ctrl: ctrl}
	mock.recorder = &MockIPetRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPetRepository) EXPECT() *MockIPetRepositoryMockRecorder {
	return m.recorder
}

// DeletePet mocks base method.
func (m *MockIPetRepository) DeletePet(arg0 string) (*entities.PetDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePet", arg0)
	ret0, _ := ret[0].(*entities.PetDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePet indicates an expected call of DeletePet.
func (mr *MockIPetRepositoryMockRecorder) DeletePet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePet", reflect.TypeOf((*MockIPetRepository)(nil).DeletePet), arg0)
}

// FindAll mocks base method.
func (m *MockIPetRepository) FindAll() ([]entities.PetDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]entities.PetDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIPetRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIPetRepository)(nil).FindAll))
}

// FindByOwnerID mocks base method.
func (m *MockIPetRepository) FindByOwnerID(arg0 string) ([]entities.PetDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOwnerID", arg0)
	ret0, _ := ret[0].([]entities.PetDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOwnerID indicates an expected call of FindByOwnerID.
func (mr *MockIPetRepositoryMockRecorder) FindByOwnerID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOwnerID", reflect.TypeOf((*MockIPetRepository)(nil).FindByOwnerID), arg0)
}

// InsertPet mocks base method.
func (m *MockIPetRepository) InsertPet(arg0 entities.CreatedPetModel) (*entities.PetDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPet", arg0)
	ret0, _ := ret[0].(*entities.PetDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertPet indicates an expected call of InsertPet.
func (mr *MockIPetRepositoryMockRecorder) InsertPet(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPet", reflect.TypeOf((*MockIPetRepository)(nil).InsertPet), arg0)
}

// UpdatePet mocks base method.
func (m *MockIPetRepository) UpdatePet(arg0 string, arg1 entities.UpdatePetModel) (*entities.PetDataModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePet", arg0, arg1)
	ret0, _ := ret[0].(*entities.PetDataModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePet indicates an expected call of UpdatePet.
func (mr *MockIPetRepositoryMockRecorder) UpdatePet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePet", reflect.TypeOf((*MockIPetRepository)(nil).UpdatePet), arg0, arg1)
}
