// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/admin": {
            "post": {
                "description": "create new admin user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "create admin",
                "parameters": [
                    {
                        "description": "Admin user data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreatedUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/login/{role}": {
            "post": {
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role of the user",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "email and password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.LoginUserRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Cannot login user: invalid password or email",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/password": {
            "post": {
                "description": "reset password with token from email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token from email",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "user new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UserPasswordModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/password/email": {
            "post": {
                "description": "forgot password and send reset link to email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "forgot password",
                "parameters": [
                    {
                        "description": "user email and role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UserSendEmailModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/register/{role}": {
            "post": {
                "description": "Register new user except admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role of the user except admin",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreatedUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/token": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates the JWT token passed in the Authorization header and decodes it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Check JWT token validity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cJWT token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token is valid",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "User not found.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get all services for the authenticated user (owner)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "get all services of current user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cJWT token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "owner creates their own booking; admins may create on behalf of an owner by providing owner_id in the payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "create service booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cJWT token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "service data (admins must include owner_id)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "owner deletes their service booking by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "delete service booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cJWT token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid service ID",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "Service not found",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/user/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "find user by id and role from JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "find user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cJWT token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "User not found.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete user by id and role from JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cJWT token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete user by id and role from JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003cJWT token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "update user data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.UserDataModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.Role": {
            "type": "string",
            "enum": [
                "admin",
                "owner",
                "doctor",
                "caretaker"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleOwner",
                "RoleDoctor",
                "RoleCaretaker"
            ]
        },
        "entities.CreateServiceRequest": {
            "type": "object",
            "required": [
                "owner_id",
                "payment_id",
                "pet_id",
                "price",
                "reserve_date",
                "status"
            ],
            "properties": {
                "owner_id": {
                    "type": "string"
                },
                "payment_id": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "price": {
                    "type": "integer",
                    "minimum": 0
                },
                "reserve_date": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "wait",
                        "ongoing",
                        "finish"
                    ]
                }
            }
        },
        "entities.CreatedUserModel": {
            "type": "object",
            "required": [
                "address",
                "birth_date",
                "email",
                "name",
                "password",
                "telephone_number"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "license_number": {
                    "description": "doctor only",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "specialization": {
                    "description": "caretaker only (optional)",
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                }
            }
        },
        "entities.LoginUserRequestModel": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "entities.ResponseMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "entities.ResponseModel": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "entities.UpdateUserModel": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_work_time": {
                    "description": "doctor/caretaker only",
                    "type": "string"
                },
                "license_number": {
                    "description": "doctor only",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "rating": {
                    "description": "caretaker only",
                    "type": "number"
                },
                "specialization": {
                    "description": "caretaker only",
                    "type": "string"
                },
                "start_date": {
                    "description": "doctor only",
                    "type": "string"
                },
                "start_work_time": {
                    "description": "doctor/caretaker only",
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                },
                "total_spending": {
                    "description": "owner only",
                    "type": "number"
                }
            }
        },
        "entities.UserDataModel": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_work_time": {
                    "type": "string"
                },
                "license_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "role": {
                    "$ref": "#/definitions/db.Role"
                },
                "specialization": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "start_work_time": {
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                },
                "total_spending": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "entities.UserPasswordModel": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "entities.UserSendEmailModel": {
            "type": "object",
            "required": [
                "email",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/db.Role"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and then your JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "lama-pet-care-backend-qbwz.onrender.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"https"},
	Title:            "LAMA Backend API",
	Description:      "this is a backend REST API server for LAMA project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
