// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin-only endpoint that returns paginated users with an optional role filter.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "list users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by role (admin, owner, caretaker, doctor)",
                        "name": "role",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of users per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/admin/users/{userID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "admin delete user by specifying user ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user by admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/admin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "create new admin user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "create admin",
                "parameters": [
                    {
                        "description": "Admin user data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreatedUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/login/{role}": {
            "post": {
                "security": [],
                "description": "Login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role of the user",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "email and password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.LoginUserRequestModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Cannot login user: invalid password or email",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/password": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "reset password with token from email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "reset password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token from email",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "user new password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.PasswordModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/password/email": {
            "post": {
                "security": [],
                "description": "forgot password and send reset link to email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "forgot password",
                "parameters": [
                    {
                        "description": "user email and role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.SendEmailModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/register/{role}": {
            "post": {
                "security": [],
                "description": "Register new user except admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Role of the user except admin",
                        "name": "role",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreatedUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/auth/token": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Validates the JWT token passed in the Authorization header and decodes it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Check JWT token validity",
                "responses": {
                    "200": {
                        "description": "Token is valid",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "User not found.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/leaveday/{day}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create Staff leaveday by token and day params (format: YYYY-MM-DD)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Leaveday"
                ],
                "summary": "Create Leaveday",
                "parameters": [
                    {
                        "type": "string",
                        "description": "leaveday",
                        "name": "day",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "request successfully",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "User not found.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all payments. Admins can see all payments, while owners can only see their own. Can be filtered by month and year. If only the 'year' query is provided, 'month' will default to 1 (January). Supports pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Get payments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter payments by month (1-12)",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter payments by year (e.g. 2025)",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 5,
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved payments",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/payments/{paymentID}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the status of a payment by its ID. Only admins are authorized to perform this action can update only status type and paydate.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payment"
                ],
                "summary": "Update payment status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "paymentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "payment update data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated payment status",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "Payment not found.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/pets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "admin can fetch all pets",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "get all pets",
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "owner can create a pet (only role == \"owner\")",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "create pet",
                "parameters": [
                    {
                        "description": "pet payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreatedPetModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/pets/owner": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "owner can get their own pets. This endpoint is owner-only and the owner ID is",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "get owner's pets",
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid owner ID",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/pets/{petID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "owner or admin can delete a pet. If role is owner, the pet must belong to the owner.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "delete pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pet id",
                        "name": "petID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid pet ID",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role or not owner's pet",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "pet not found",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "owner or admin can update a pet. If role is owner, the pet must belong to the owner.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pet"
                ],
                "summary": "update pet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "pet id",
                        "name": "petID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "pet payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdatePetModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid pet ID or no fields to update",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role or not owner's pet",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "pet not found",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all services for the authenticated user. Admins can see all services. Can be filtered by status, month, and year.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Get services",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter services by status (e.g. all, wait, ongoing, finish)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter services by month (1-12)",
                        "name": "month",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter services by year (e.g. 2025)",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number for pagination",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Owners create their own bookings; admins may create on behalf of an owner by providing owner_id. Use service_type=cservice (caretaker) or mservice (doctor) and supply staff_id plus type-specific fields. this route then create payment and send those to stripe to get payment link.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Create caretaker/medical service by stripe payment",
                "parameters": [
                    {
                        "description": "service payload (admins must include owner_id; mservice requires disease)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/review/{serviceID}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Owner-only endpoint to review cservice. The caller must be the owner of the service and the service must be finished. Either ` + "`" + `score` + "`" + ` or ` + "`" + `comment` + "`" + ` (or both) must be provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Update cservice score and review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "serviceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review payload (score: integer 1-5, comment: optional)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.ReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid request or missing fields",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role or owner mismatch",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "Service not found",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/staff": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all staff members available for a specific service type on a given day.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Get available staff",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service type to check availability for (cservice or mservice)",
                        "name": "serviceType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service mode (full-day or partial)",
                        "name": "serviceMode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service start date (format: YYYY-MM-DD)",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service end date (format: YYYY-MM-DD)",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/staff/{staffID}/score": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve average score and list of reviews for a caretaker (staff). Owners and admins can view any caretaker; a caretaker may view their own reviews. If ` + "`" + `staffID` + "`" + ` is omitted and the caller is a caretaker, the handler defaults to the caller's ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Get score and reviews",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staff ID (caretaker). If omitted and caller is caretaker, defaults to caller's ID",
                        "name": "staffID",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/staff/{staffID}/time": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve all busy time slot for a specific staff on a given day.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Get busy time slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service type to check availability for (cservice or mservice)",
                        "name": "serviceType",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service start date (format: YYYY-MM-DD)",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "service end date (format: YYYY-MM-DD)",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "StaffID",
                        "name": "staffID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/{serviceID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "owner deletes their service booking by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "delete service booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Delete successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "400": {
                        "description": "Invalid service ID",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "Service not found",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin-only endpoint for adjusting service data. Provide the fields that need to change.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Update service booking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "serviceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "service update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "Service not found",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/services/{serviceID}/{status}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the status of a service booking. Allowed roles: admin, caretaker, doctor.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "Update service status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "serviceID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "wait",
                            "ongoing",
                            "finish"
                        ],
                        "type": "string",
                        "description": "service status (wait, ongoing, finish)",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "403": {
                        "description": "Invalid role",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "404": {
                        "description": "Service not found",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        },
        "/user/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "find user by id and role from JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "find user by id",
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "User not found.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete user by id and role from JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user by id",
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseModel"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete user by id and role from JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user by id",
                "parameters": [
                    {
                        "description": "update user data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateUserModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.UserDataModel"
                        }
                    },
                    "400": {
                        "description": "Invalid json body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/profile": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update user picture by id and role from JWT token",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "update user picture",
                "parameters": [
                    {
                        "type": "file",
                        "description": "user profile picture",
                        "name": "profile",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Request successful",
                        "schema": {
                            "$ref": "#/definitions/entities.UserDataModel"
                        }
                    },
                    "400": {
                        "description": "picture file is required",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "401": {
                        "description": "Unauthorization Token.",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.PetSex": {
            "type": "string",
            "enum": [
                "male",
                "female",
                "unknown"
            ],
            "x-enum-varnames": [
                "PetSexMale",
                "PetSexFemale",
                "PetSexUnknown"
            ]
        },
        "db.Role": {
            "type": "string",
            "enum": [
                "admin",
                "owner",
                "doctor",
                "caretaker"
            ],
            "x-enum-varnames": [
                "RoleAdmin",
                "RoleOwner",
                "RoleDoctor",
                "RoleCaretaker"
            ]
        },
        "entities.CreateServiceRequest": {
            "type": "object",
            "required": [
                "pet_id",
                "reserve_date_end",
                "reserve_date_start",
                "service_type",
                "staff_id",
                "status"
            ],
            "properties": {
                "disease": {
                    "type": "string",
                    "minLength": 1
                },
                "owner_id": {
                    "type": "string"
                },
                "payment_id": {
                    "description": "for backend",
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "reserve_date_end": {
                    "type": "string"
                },
                "reserve_date_start": {
                    "type": "string"
                },
                "service_type": {
                    "type": "string",
                    "enum": [
                        "mservice",
                        "cservice"
                    ]
                },
                "staff_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "wait",
                        "ongoing",
                        "finish"
                    ]
                }
            }
        },
        "entities.CreatedPetModel": {
            "type": "object",
            "required": [
                "birth_date",
                "kind",
                "owner_id",
                "sex",
                "weight"
            ],
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "sex": {
                    "enum": [
                        "male",
                        "female",
                        "unknown"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/db.PetSex"
                        }
                    ]
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "entities.CreatedUserModel": {
            "type": "object",
            "required": [
                "address",
                "birth_date",
                "email",
                "name",
                "password",
                "telephone_number"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "license_number": {
                    "description": "doctor only",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "specialization": {
                    "description": "caretaker only (optional)",
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                }
            }
        },
        "entities.LoginUserRequestModel": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "entities.PasswordModel": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "entities.ResponseMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "entities.ResponseModel": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "entities.ReviewRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1
                },
                "score": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                }
            }
        },
        "entities.SendEmailModel": {
            "type": "object",
            "required": [
                "email",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/db.Role"
                }
            }
        },
        "entities.UpdatePaymentRequest": {
            "type": "object",
            "properties": {
                "pay_date": {
                    "description": "validate datetime แบบ RFC3339 (แบบเดียวกับที่โค้ดเก่าคุณพยายาม Parse)",
                    "type": "string"
                },
                "status": {
                    "description": "ล้อตาม enum payment_status ของคุณ",
                    "type": "string",
                    "enum": [
                        "UNPAID",
                        "PAID"
                    ]
                },
                "type": {
                    "description": "สมมติว่า Type มีได้ 2 แบบ (คุณไปแก้ได้)",
                    "type": "string",
                    "minLength": 1
                }
            }
        },
        "entities.UpdatePetModel": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "breed": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "sex": {
                    "$ref": "#/definitions/db.PetSex"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "entities.UpdateServiceRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string",
                    "minLength": 1
                },
                "disease": {
                    "type": "string",
                    "minLength": 1
                },
                "owner_id": {
                    "type": "string"
                },
                "pet_id": {
                    "type": "string"
                },
                "reserve_date_end": {
                    "type": "string"
                },
                "reserve_date_start": {
                    "type": "string"
                },
                "score": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                },
                "staff_id": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "wait",
                        "ongoing",
                        "finish"
                    ]
                }
            }
        },
        "entities.UpdateUserModel": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_work_time": {
                    "description": "doctor/caretaker only",
                    "type": "string"
                },
                "license_number": {
                    "description": "doctor only",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "rating": {
                    "description": "caretaker only",
                    "type": "number"
                },
                "specialization": {
                    "description": "caretaker only",
                    "type": "string"
                },
                "start_date": {
                    "description": "doctor only",
                    "type": "string"
                },
                "start_work_time": {
                    "description": "doctor/caretaker only",
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                },
                "total_spending": {
                    "description": "owner only",
                    "type": "number"
                }
            }
        },
        "entities.UserDataModel": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "birth_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "end_work_time": {
                    "type": "string"
                },
                "license_number": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                },
                "rating": {
                    "type": "number"
                },
                "role": {
                    "$ref": "#/definitions/db.Role"
                },
                "show_id": {
                    "type": "integer"
                },
                "specialization": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "start_work_time": {
                    "type": "string"
                },
                "telephone_number": {
                    "type": "string"
                },
                "total_spending": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and then your JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [
        {
            "BearerAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "lama-pet-care-backend-dev.onrender.com",
	BasePath:         "/api/v1",
	Schemes:          []string{"https"},
	Title:            "LAMA Backend API",
	Description:      "this is a backend REST API server for LAMA project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
